version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockertest78921
    ports:
      - 80:80
    environment:
      - PORT=80
    volumes:
      - ./project/:/var/www/html/
